config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/ahctaw', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get '/users/auth/kakao', to: 'users/omniauth_callbacks#kakao'
    get '/users/auth/kakao/callback', to: 'users/omniauth_callbacks#kakao_auth'
  end
  
  root 'movies#index'
  
  resources :movies do
    member do #자동으로 id에 setting이 됨
      post '/comments' => 'movies#create_comment'
    end
    
    collection do
      delete '/comments/:comment_id' => 'movies#destroy_comment'
      patch '/comments/:comment_id' => 'movies#update_comment'
      get '/search_movie' => 'movies#search_movie'
    end
    # collection do
    #   get '/test' => 'movies#test'
    # end
  end
  
  post '/uploads' => 'movies#upload_image'
  
  get '/likes/:movie_id' => 'movies#like_movie'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
before_action :js_authenticate_user!, only: [:like_movie, :create_comment, :destroy_comment, :update_comment]
before_action :authenticate_user!, except: [:index, :show, :search_movie]
before_action :set_movie, only: [:show, :edit, :update, :destroy, :create_comment]  
  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.page(params[:page])
  @users = User.order(:name).page params[:page]
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
      @user_likes_movie = Like.where(user_id: current_user.id, movie_id: @movie.id).first #where는 객체를 리턴하기 때문에 first를 써야함.
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)
    @movie.user_id = current_user.id
    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' } #html로 요청이 오면 html로 보내주고
        format.json { render :show, status: :ok, location: @movie } #json으로 요청이 오면 json으로 보내준다.
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like_movie
    p params
    # 현재 유저와 params에 담긴 movie간의 
    # 좋아요 관계를 설정한다. 끗
    
    @like =Like.where(user_id:current_user.id, movie_id:params[:movie_id]).first #where는 리턴이 배열이므로 얘의 첫번째를 찾아줘야함.
    if @like.nil?
      @like = Like.create(user_id: current_user.id, movie_id: params[:movie_id])
    else
      @like.destroy
    end
    # @like.frozen? #삭제됐을경우 삭제되지 못하게 얼어있는다. 삭제된 경우가 좋아요 취소된 경우임. true라면 좋아요 취소 로직을 넣고, 아니면 좋아요가 새로 눌린 경우로 생각하면됨.
    # 만약에 현재 로그인한 유저가 이미 좋아요를 눌렀을 경우
    # 해당 Like 인스턴스 삭제
    # 새로 누른 경우
    # 좋아요 관계 설정
    
  end
  
  
  def create_comment
    @comment = Comment.create(user_id: current_user.id, movie_id: @movie.id, contents: params[:contents])
    #@movie.comments.new(user_id:current_user.id, movie_id: @movie.id)
    
  end

  def destroy_comment
    @comment = Comment.find(params[:comment_id]).destroy()
  end
  
  def update_comment
    @comment = Comment.find(params[:comment_id])
    @comment.update(contents: params[:contents])
  end
  
  def search_movie
    respond_to do |format|
      if params[:q].strip.empty? #빈 공백(스페이스)을 인식하지 못하도록 strip해버림
        format.js {render 'no_content'} # 내가 원하는(action명과 일치하는) 자바스크립트 파일을 보내줄 수 있다고 생각하면 됨.
      else                              # 즉, no_content.js.erb를 찾아서 보내줌.
        @movies = Movie.where("title LIKE ?","#{params[:q]}%") # q의 내용으로 시작하는 결과를 찾음.
        format.js {render 'search_movie'}
      end
    end
  end
  
  def upload_image
    @image = Image.create(image_path: params[:upload][:image])
    render json: @image
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :genre, :director, :actor, :description, :image_path)
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_for(movie) do |f| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
	<%= f.label :title %>
	<%= f.text_field :title, class: "form-control" %>
</div>
        
<div class="form-group">
	<%= f.label :genre %>
	<%= f.text_field :genre, class: "form-control" %>
</div>
        
<div class="form-group">
	<%= f.label :director %>
	<%= f.text_field :director, class: "form-control" %>
</div>

<div class="form-group">
	<%= f.label :actor %>
	<%= f.text_field :actor, class: "form-control" %>
</div>
        
<div class="form-group">
	<%= f.label :description %>
	<%= f.text_area :description, 'data-provider': :summernote %>
</div>

<div class="form-group">
	<%= f.label :image_path %>
	<%= f.file_field :image_path, class: "form-control" %>
</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/create_comment.js.erb
$('.comment-list').prepend(`
        <li class="comment-<%= @comment.id %> list-group-item d-flex justify-content-between">
        <span class="comment-detail-<%=@comment.id%>"><%= @comment.contents %></span>
        <div>
            <button data-id="<%= @comment.id %>" class="btn btn-warning text-white edit-comment">수정</button>
            <button data-id="<%= @comment.id %>" class="btn btn-danger destroy-comment">삭제</button></small>
        </div>
    </li>`);
$('.comment-contents').val('')

app/views/movies/destroy_comment.js.erb
alert("댓글이 삭제 되었습니다.");
$('.comment-<%= @comment.id %>').remove();

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h1 id="title"> Movies </h1>
<input type="text" class="form-control movie-title">
<div class="recomm-movie d-flex justify-content-start row">
    
</div>
<div id="title" class="row">
<% @movies.each do |movie| %>
<div class="card col-md-3"> <!-- 몇칸을 차지할지 지정 -->
    <img class="card-img-top" src="<%= movie.image_path.thumb.url %>" alt="">
    <div class="card-body">
        <h5 class="card-title" data-id="3" aabbcc="ddeeff"><span><%= movie.title %></span></h5>
        <p class="card-text">장르: <%=movie.genre %></p>
        <p class="card-text">감독: <%=movie.director %></p>
        <p class="card-text">배우: <%=movie.actor %></p>
        <p class="card-text">설명: <%=movie.description %></p>
        <%= link_to '영화정보보기', movie_path(movie),class: 'btn btn-primary' %>
	</div>
</div>

<% end %>
</div>
<%= paginate @movies, theme: 'twitter-bootstrap-4' %>
<hr>

<br>

<br>

<%= link_to 'New Movie', new_movie_path %>

<hr>

<% if user_signed_in? %>

<!-- 로그인 된 상태-->

<%= current_user.email %>

<%= link_to "로그아웃", destroy_user_session_path, method: "delete" %>

<% else %>

<!-- 로그아웃 된 상태-->

<%= link_to "로그인", new_user_session_path %>

<% end %>

<script>
$(document).on('ready', function() {
    $('.movie-title').on('keyup', function(){
        $('.recomm-movie').html('');
        var title = $(this).val();
        
        $.ajax({
            url: '/movies/search_movie',
            data: {
                q: title
            }
        });
    })
});
/*    var btn = document.getElementsByClassName("btn")[0];
    var count = 0;
    var msg = "나 건드리지마!!";
    
    btn.onmouseover = function(){ 
        count++; 
        if (count > 3) {
            msg = "아 진짜 짜증나니까 나 건드리지 말라고!!!";
        }
    
        alert(msg);
    }*/

// func1(); //실행안됨
// func2(); //실행됨

// var func1 = function(){ //함수 표현식 - 선언 이후로 사용할 수 있음. 
//     alert("하위~");
// }
// function func2() { //함수 선언식 - 즉, 선언되기 이전에 사용될 수 있음
//     alert("하위~2");
// }

// var btn = document.getElementsByClassName("btn")[0];
// // btn.addEventListener("mouseover",func2()); //error. 괄호를 빼야함
// btn.addEventListener("mouseover",func2);
// var btn2 = document.getElementsByClassName("btn")[1]
// // btn2.onmouseover = func1(); //error. 얘도 ()괄호 빼야함
// btn2.onmouseover = func1;

// 먼저 선언되어 있던 함수를 이벤트 핸들러로 사용할 경우
// 함수 이름만 적어서 사용한다.
// 함수 이름() <- 이 형태는 함수의 실행을 의미한다.

// 버튼(요소)에 마우스를 오버(이벤트)했더니(이벤트 리스터) 
// 그 위에있던 글자(요소)들이 갑자기 이상한 글자로 변해버린다(이벤트 핸들러).
// var count = 0;
// var title = document.getElementsByClassName("card-title")[0];
// console.dir(title);
// var save_title = title.innerText;
// //innerHtml과 innerText의 차이점
// //innerHTML은 개발자 코드로 확인할 때, 코드 전체를 보여주고, innerText는 결과만 리턴함.
// var btn = document.getElementsByClassName("btn")[0];
// btn.addEventListener("mouseover",function(){
//     var title = document.getElementsByClassName("card-title")[0];
    
//     if(count % 2 == 0)
//     {
//         console.dir(title);
//         title.innerText = "Don't touch me!";    
//         count++;
//     }
//     else{
//         console.dir(title);
//         title.innerText = save_title;
//         count++;
//     }
    
// }//익명 함수
// );


// 버튼(요소)에 마우스를 올리면(이벤트, 이벤트 리스너)
// 해당 버튼(요소)의 class가 btn btn-danger로 변함.(이벤트 핸들러)
// var btn = document.getElementsByClassName("btn")[0];
// btn.addEventListener("mouseover",function(){
//   btn.setAttribute("class","btn btn-danger");     
// })

// btn.addEventListener("mouseout",function(){
//   btn.setAttribute("class","btn btn-primary");     
// })

</script>

app/views/movies/like_movie.js.erb
var like_count = parseInt($('.like-count').text());

if(<%=@like.frozen?%>){
    <!--frozen 이 true 좋아요 눌린인간이 취소함 다시 좋아요 표시 되게끔함-->
    like_count = like_count -1
    $('.like').html(`좋아요(<span class='like-count'>${like_count}</span>)`).addClass("btn-primary").removeClass("btn-warning");
   
     
}else{
    like_count = like_count +1
     $('.like').html(`좋아요 취소(<span class="like-count">${like_count}</span>)`).addClass("btn-warning").removeClass("btn-primary");
    
     
}
//좋아요가 취소된 경우
// 좋아요 취소버튼 -> 좋아요 버튼

//좋아요가 새로 눌린 경우
//좋아요 버튼 -> 좋아요 취소버튼으로 

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/search_movie.js.erb
console.log("찾았다");
$('.recomm-movie').html(`
<% @movies.each do |movie| %>
<span class="badge badge-primary"><%= movie.title %></span> &nbsp&nbsp
<% end %>
`);

app/views/movies/show.html.erb
<h1><%=@movie.title%></h1>
<hr>
<img class="card-img-top" src="<%= @movie.image_path.thumb.url %>" alt="">
<p><%= simple_format(@movie.description)%></p> <!-- url주소를 img로 바꿔줌. -->
<%= link_to 'Edit', edit_movie_path(@movie) %> 
<%= link_to 'Back', movies_path %>
<hr>
<% if(@user_likes_movie.nil?)%>
    <button class="btn btn-info like">좋아요(<span class='like-count'><%=@movie.likes.count%></span>)</button>
<%else%>
    <button class="btn btn-warning text-white like">좋아요 취소(<span class='like-count'><%=@movie.likes.count%></span>)</button>
<%end%>
<hr>
<form class="text-right comment">
    <input class="form-control comment-contents">
    <input type="submit" value="댓글쓰기" class="btn btn-success">
</form>
<h3>댓글</h3>
<ul class="list-group comment-list">
    <!--<li class="list-group-item">Cras justo odio</li>-->
    <!--기존에 등록되어 있는 댓글 출력하기 -->
    <% @movie.comments.reverse.each do |comm| %>
        <li class="comment-<%= comm.id %> list-group-item d-flex justify-content-between">
            <span class="comment-detail-<%=comm.id%>"><%= comm.contents %>...(<%= comm.user.email %>)</span>
        
        <div>
            <button data-id="<%= comm.id %>" class="btn btn-warning text-white edit-comment">수정</button>
            <button data-id="<%= comm.id %>" class="btn btn-danger destroy-comment">삭제</button></small>
        </div>
        </li>
    <% end %>
</ul>
<hr>
<script>
    $(document).ready(function(){
        $('.like').on('click',function(){
            console.log("like!!!");
            $.ajax({
                url:'/likes/<%=@movie.id%>'
            });
        })
        $('.comment').on('submit', function(e){
            
            e.preventDefault();
           var comm = $('.comment-contents').val(); 
           console.log(comm);

           $.ajax({
               url: "/movies/<%= @movie.id %>/comments",
               method: "POST",
               data: {
                   contents: comm
               }
           });
        });
        
        // $('.destroy-comment').on('click',function(){
            $(document).on('click','.destroy-comment',function(){
            console.log("destroyed!!!");
            
            var comment_id = $(this).attr('data-id');
            //$(this).data('id');
            console.log(comment_id);
            $.ajax({
               url: "/movies/comments/"+comment_id,
               method: "delete"
            });
        });
        
        $(document).on('click','.edit-comment',function(){
           var comment_id = $(this).data('id');
           var edit_comment = $(`.comment-detail-${comment_id}`);
           var contents = edit_comment.text();
           edit_comment.html(`<input type="text" value="${contents}" class="form-control edit-comment-${comment_id}">`);
           $(this).text("확인").removeClass("edit-comment btn-warning").addClass("update-comment btn-dark");
        });
        
        $(document).on('click','.update-comment',function(){
            var comment_id = $(this).data('id');
            var comment_form = $(`.edit-comment-${comment_id}`)
            
            $.ajax({
               url: "/movies/comments/" + comment_id, 
               method: "patch",
               data: {
                   contents: comment_form.val()
               }
            });
        });
    });

</script>

app/views/movies/update_comment.js.erb
alert("수정완료");
var edit_comment = $('.comment-detail-<%= @comment.id %>');
edit_comment.html('<%= @comment.contents %>');
$('.update-comment').text("수정").removeClass("update-comment btn-dark").addClass("edit-comment btn-warning");